language: python
python:
  - "3.6" 
install:
  - pip install -e .
  - pip install pytest-cov codecov # Install packages for code coverage report.
  - name: Codecov
    uses: codecov/codecov-action@v1.5.2
script:
  - pytest --cov=src tests # Point to the source directory. This will run the test and produce a coverage report.
after_success:
  - codecov # This makes Travis.CI push the code coverage results to Codecov after every build.